### ISSUE TITLE
Moons?

### ISSUE THREAD

**Issue by ajtribick** [OpenExoplanetCatalogue/open_exoplanet_catalogue#1087]
It might be useful to have a `<moon>` element available.

**Comment by larsnaesbye** [comment]
Makes sense, given that chances of having an exomoon confirmed sometime soon are pretty good.
Should any parameters differ from the `<planet>` element, you think?

**Comment by SevenSpheres** [comment]
Was support for moons ever added? Currently, the exomoon candidate [Kepler-1708 b-i](https://arxiv.org/abs/2201.04643) is [included in the database](http://www.openexoplanetcatalogue.com/planet/Kepler-1708%20b-i/) as a planet orbiting the star Kepler-1708, instead of a moon orbiting the planet Kepler-1708 b. This should be corrected, or the exomoon candidate should be removed.
