### ISSUE TITLE
Add mass of Kepler-78

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/open_exoplanet_catalogue#438]
http://arxiv.org/abs/1501.00369

**Comment by ajtribick** [comment]
Also check the paper referenced in #284 (probably best to resolve both of these in one go)

**Comment by Nexusty** [comment]
Just saw your comment after committing. That's what I was thinking of however they mentioned in the paper Hanno posted in this issue that the reason they don't rely so heavily on previous papers is due to the deviation being too big. That's the same reason they barely used any of the properties given by Sanchis-Ojedas et al.

**Comment by hannorein** [comment]
I've closed #284, but we still need to complete the entry for this system. Specifically, go over the paper http://arxiv.org/abs/1407.0853


Why did we not add this one in 2013?
